### PR TITLE
Fix case of version and verbose option alias in README

### PR DESCRIPTION
**Pull request by seiffert**
According to https://github.com/Jimdo/github-sync-labels-milestones/blob/master/cli.js#L10-L11, `-V` is an alias for `--version` and `-v` for `--verbose`.

### CODE REVIEW

**Comment by seiffert** [comment]
PTAL @Xiphe

**Comment by Xiphe** [comment]
what was i thinking?!?

**Comment by Xiphe** [comment]
thanks :P

**Comment by seiffert** [comment]
:smile:

**Pull request merged**
